SELECT P.NOME,COUNT(*) AS N_PEZZIDIRICAMBIO
FROM PEZZIDIRICAMBIO P
GROUP BY P.NOME
HAVING N_PEZZIDIRICAMBIO>=ALL(SELECT COUNT(*) AS N_PEZZIDIRICAMBIO
							FROM PEZZIDIRICAMBIO P
                            GROUP BY P.NOME)
                            
                            